theme: jekyll-theme-cayman
show_downloads: true
github:
  apple_url: https://apps.apple.com/us/app/id1522389053
  microsoft_url: https://www.microsoft.com/store/apps/9NXGN9LJTL05
  zip_url: https://github.com/yongchaofan/FLTerm/releases/download/2.0.0/FLTerm-2.0.0.zip
  description: fast light terminal emulator
